# Generated by Django 3.0.5 on 2020-04-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=60)),
                ('middle', models.CharField(max_length=60)),
                ('last', models.CharField(max_length=60)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
    ]
