# Generated by Django 3.0.5 on 2020-04-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling_site', '0007_auto_20200424_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='bowler1',
        ),
        migrations.AddField(
            model_name='team',
            name='Bowler(s)',
            field=models.ManyToManyField(to='bowling_site.Bowler'),
        ),
        migrations.AlterField(
            model_name='team',
            name='avg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='hdcp',
            field=models.FloatField(null=True),
        ),
    ]
