# Generated by Django 3.0.5 on 2020-04-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling_site', '0008_auto_20200424_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bowler',
            options={'ordering': ['last']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['teamid']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='bowler',
            name='avg',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bowler',
            name='hdcp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='avg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='hdcp',
            field=models.FloatField(),
        ),
    ]
