# Generated by Django 3.0.5 on 2020-04-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling_site', '0009_auto_20200426_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='hdcp',
            field=models.FloatField(null=True),
        ),
    ]
